---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: raft
  name: raft
  namespace: raft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raft
  name: raft
  namespace: raft
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: raft
  template:
    metadata:
      labels:
        app: raft
    spec:
      containers:
        - args:
            - placeholder
          command:
            - raft
          image: raft:0.0.1
          imagePullPolicy: Never # Pull local docker image.
          name: raft
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: raft
  name: raft
  namespace: raft
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: raft
  type: ClusterIP
